### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by yariks** [tomlankhorst/kohana-3.3-mysqli#6]
Hi
Just updated and receive this error:

ErrorException [ 4096 ]: Argument 3 passed to mysqli_fetch_object() must be of the type array, null given ~ MODPATH/mysqli-driver/classes/Database/MySQLi/Result.php [ 62 ]

Cheers

**Comment by tomlankhorst** [comment]
Thank you, PR is reverted. Discussing now.

**Comment by tomlankhorst** [comment]
Thanks for fast response. I've reverted the PR

Tom Lankhorst

​
http://webhub.nl/
m. +31 (0)6 307 41 869
e. info@tomlankhorst.nl  Meeuwenstraat 54
7523 XV Enschede

2015-05-26 11:53 GMT+02:00 yariks notifications@github.com:

**Comment by tomlankhorst** [comment]
Hi Yariks,

What version of MySqli are you using in PHP?

Kind regards,

Tom Lankhorst

​
http://webhub.nl/
m. +31 (0)6 307 41 869
e. info@tomlankhorst.nl  Meeuwenstraat 54
7523 XV Enschede

2015-05-26 11:53 GMT+02:00 yariks notifications@github.com:

**Comment by hemulya** [comment]
php-mysql version: 5.5.9+dfsg-1ubuntu4.9

coused when do:
php index.php db:migrate

> PR is reverted

thanks
